query GET_RECIPES($account: String, $acronym: String, $fields: [String]) {
  documents(account: $account, acronym: $acronym, fields: $fields)
    @context(provider: "vtex.store-graphql@2.157.1") {
    fields {
      key
      value
    }
  }
}
